env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  {
    react/react-in-jsx-scope: 0,
    require-jsdoc: 0,
    object-curly-spacing: 0,
    indent: [2, 2],
    comma-dangle: 0,
    arrow-parens: 0,
    linebreak-style: 0,
    semi: 0,
    eol-last: 0,
  }
